#!/usr/bin/env python3
"""Diff rrng against golden vectors generated by REAL R (see generate_golden.R).

Run directly:
    /glade/u/apps/opt/conda/envs/npl-2025b/bin/python rrng/tests/test_rrng.py
or under pytest:
    python -m pytest rrng/tests
"""
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from rrng import RRNG

FIXTURE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "golden_vectors.json")
RUNIF_TOL = 1e-9   # R prints/stores doubles; rrng floats match to full double precision


def _load():
    with open(FIXTURE) as f:
        return json.load(f)


def _check_case(c):
    if c["type"] == "runif":
        g = RRNG(c["seed"])
        got = g.runif(c["n"])
        exp = np.asarray(c["expected"], dtype=float)
        err = float(np.max(np.abs(got - exp)))
        assert err <= RUNIF_TOL, f"runif seed={c['seed']} max|err|={err:.2e}"
        return f"runif  seed={c['seed']:<7} n={c['n']:<3} max|err|={err:.1e}"
    elif c["type"] == "sample":
        g = RRNG(c["seed"], sample_kind=c["sample_kind"])
        got = g.sample_index(c["n"], c["size"])
        exp = np.asarray(c["expected"], dtype=np.int64)
        assert np.array_equal(got, exp), (
            f"sample[{c['sample_kind']}] seed={c['seed']} n={c['n']}: "
            f"got {got[:12].tolist()}... != {exp[:12].tolist()}...")
        return f"sample[{c['sample_kind']:<9}] seed={c['seed']:<7} n={c['n']:<7} size={c['size']:<6} EXACT"
    elif c["type"] == "stream":
        # ONE seed stream, interleaved runif/sample consumed in order (the key feature).
        g = RRNG(c["seed"], sample_kind=c["sample_kind"])
        for k, op in enumerate(c["ops"]):
            exp = op["expected"]
            if op["op"] == "runif":
                got = g.runif(op["n"])
                err = float(np.max(np.abs(got - np.asarray(exp, dtype=float))))
                assert err <= RUNIF_TOL, f"stream seed={c['seed']} op{k} runif max|err|={err:.2e}"
            else:  # sample
                got = g.sample_index(op["n"], op["size"])
                assert np.array_equal(got, np.asarray(exp, dtype=np.int64)), (
                    f"stream seed={c['seed']} op{k} sample(n={op['n']}): "
                    f"got {got.tolist()} != {exp}")
        return f"stream seed={c['seed']:<7} {len(c['ops'])} interleaved ops EXACT"
    raise ValueError(c["type"])


# ---- pytest entry point (parametrized) ----
def _all_cases():
    return _load()


try:
    import pytest

    @pytest.mark.parametrize("c", _all_cases())
    def test_golden(c):
        _check_case(c)
except Exception:
    pass


# ---- standalone runner ----
def main():
    cases = _load()
    ok = 0
    for c in cases:
        line = _check_case(c)        # raises AssertionError on mismatch
        ok += 1
        print(f"  PASS  {line}")
    print(f"\n{ok}/{len(cases)} golden cases match R bit-for-bit.")


if __name__ == "__main__":
    main()
