#!/usr/bin/env python3
"""Diff rrng against golden vectors generated by REAL R (see generate_golden.R).

Run directly:
    /glade/u/apps/opt/conda/envs/npl-2025b/bin/python rrng/tests/test_rrng.py
or under pytest:
    python -m pytest rrng/tests
"""
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from rrng import RRNG

FIXTURE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "golden_vectors.json")
RUNIF_TOL = 1e-9   # legacy runif fixtures stored at 17 sig digits
# Continuous variates (rnorm/rexp/rgamma) are bit-exact here; allow a hair for any
# last-ULP libm difference across machines in exp/log-heavy paths.
FLOAT_TOL = 1e-12


def _close(got, exp, tol):
    got = np.asarray(got, dtype=float)
    exp = np.asarray(exp, dtype=float)
    denom = np.maximum(np.abs(exp), 1.0)
    return float(np.max(np.abs(got - exp) / denom))


def _load():
    with open(FIXTURE) as f:
        return json.load(f)


def _check_case(c):
    if c["type"] == "runif":
        g = RRNG(c["seed"])
        got = g.runif(c["n"])
        exp = np.asarray(c["expected"], dtype=float)
        err = float(np.max(np.abs(got - exp)))
        assert err <= RUNIF_TOL, f"runif seed={c['seed']} max|err|={err:.2e}"
        return f"runif  seed={c['seed']:<7} n={c['n']:<3} max|err|={err:.1e}"
    elif c["type"] == "sample":
        g = RRNG(c["seed"], sample_kind=c["sample_kind"])
        got = g.sample_index(c["n"], c["size"])
        exp = np.asarray(c["expected"], dtype=np.int64)
        assert np.array_equal(got, exp), (
            f"sample[{c['sample_kind']}] seed={c['seed']} n={c['n']}: "
            f"got {got[:12].tolist()}... != {exp[:12].tolist()}...")
        return f"sample[{c['sample_kind']:<9}] seed={c['seed']:<7} n={c['n']:<7} size={c['size']:<6} EXACT"
    elif c["type"] == "stream":
        # ONE seed stream, interleaved runif/sample consumed in order (the key feature).
        g = RRNG(c["seed"], sample_kind=c["sample_kind"])
        for k, op in enumerate(c["ops"]):
            exp = op["expected"]
            if op["op"] == "runif":
                got = g.runif(op["n"])
                err = float(np.max(np.abs(got - np.asarray(exp, dtype=float))))
                assert err <= RUNIF_TOL, f"stream seed={c['seed']} op{k} runif max|err|={err:.2e}"
            else:  # sample
                got = g.sample_index(op["n"], op["size"])
                assert np.array_equal(got, np.asarray(exp, dtype=np.int64)), (
                    f"stream seed={c['seed']} op{k} sample(n={op['n']}): "
                    f"got {got.tolist()} != {exp}")
        return f"stream seed={c['seed']:<7} {len(c['ops'])} interleaved ops EXACT"
    elif c["type"] == "rnorm":
        got = RRNG(c["seed"]).rnorm(c["n"])
        err = _close(got, c["expected"], FLOAT_TOL)
        assert err <= FLOAT_TOL, f"rnorm seed={c['seed']} relerr={err:.2e}"
        return f"rnorm  seed={c['seed']:<7} n={c['n']:<3} relerr={err:.1e}"
    elif c["type"] == "rexp":
        got = RRNG(c["seed"]).rexp(c["n"], rate=c["rate"])
        err = _close(got, c["expected"], FLOAT_TOL)
        assert err <= FLOAT_TOL, f"rexp seed={c['seed']} rate={c['rate']} relerr={err:.2e}"
        return f"rexp   seed={c['seed']:<7} rate={c['rate']:<4} relerr={err:.1e}"
    elif c["type"] == "rgamma":
        got = RRNG(c["seed"]).rgamma(c["n"], c["shape"], scale=c["scale"])
        err = _close(got, c["expected"], FLOAT_TOL)
        assert err <= FLOAT_TOL, f"rgamma seed={c['seed']} shape={c['shape']} relerr={err:.2e}"
        return f"rgamma seed={c['seed']:<7} shape={c['shape']:<5} scale={c['scale']:<3} relerr={err:.1e}"
    elif c["type"] == "rpois":
        got = RRNG(c["seed"]).rpois(c["n"], c["mu"])
        exp = np.asarray(c["expected"], dtype=np.int64)
        assert np.array_equal(got, exp), f"rpois seed={c['seed']} mu={c['mu']}: {got.tolist()} != {exp.tolist()}"
        return f"rpois  seed={c['seed']:<7} mu={c['mu']:<5} EXACT"
    elif c["type"] == "rbinom":
        got = RRNG(c["seed"]).rbinom(c["n"], c["size"], c["prob"])
        exp = np.asarray(c["expected"], dtype=np.int64)
        assert np.array_equal(got, exp), f"rbinom seed={c['seed']} size={c['size']} prob={c['prob']}: {got.tolist()} != {exp.tolist()}"
        return f"rbinom seed={c['seed']:<7} size={c['size']:<5} prob={c['prob']:<4} EXACT"
    elif c["type"] == "sample2":
        prob = None if c["prob"] is None else np.asarray(c["prob"], dtype=float)
        g = RRNG(c["seed"], sample_kind=c.get("sample_kind", "rejection"))
        got = g.sample(c["n"], c["size"], replace=c["replace"], prob=prob)
        exp = np.asarray(c["expected"], dtype=np.int64)
        kind = "weighted" if prob is not None else "equal"
        rep = "replace" if c["replace"] else "noreplace"
        assert np.array_equal(got, exp), (
            f"sample({kind},{rep}) seed={c['seed']} n={c['n']}: {got.tolist()} != {exp.tolist()}")
        return f"sample2 seed={c['seed']:<7} n={c['n']:<5} {kind:<8} {rep:<9} EXACT"
    raise ValueError(c["type"])


# ---- pytest entry point (parametrized) ----
def _all_cases():
    return _load()


try:
    import pytest

    @pytest.mark.parametrize("c", _all_cases())
    def test_golden(c):
        _check_case(c)
except Exception:
    pass


# ---- standalone runner ----
def main():
    cases = _load()
    ok = 0
    for c in cases:
        line = _check_case(c)        # raises AssertionError on mismatch
        ok += 1
        print(f"  PASS  {line}")
    print(f"\n{ok}/{len(cases)} golden cases match R bit-for-bit.")


if __name__ == "__main__":
    main()
